apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: aks-hpa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: load-generator
          image: YOUR_ACR.azurecr.io/aks-hpa-demo:v2
          command:
            - node
            - load.js
          env:
            - name: TARGET_URL
              value: http://cpu-demo:3000/work?duration=100
            - name: CONCURRENCY
              value: "1"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi

