apiVersion: v1
kind: LimitRange
metadata:
  name: container-resource-limits
  namespace: aks-governance-demo
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 128Mi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      min:
        cpu: 50m
        memory: 32Mi
      max:
        cpu: 500m
        memory: 256Mi

